version: "3.7"

services:
    mysql:
        image: mysql:8.0.1
        restart: always
        volumes:
            - ./.data/mysql:/var/lib/mysql
            - ./.config/mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        env_file: ./.config/mysql/.env
        ports:
            - "3310:3306"
