version: "3.7"

services:
    mysql:
        image: mysql:8
        restart: always
        volumes:
            - ./.data/mysql:/var/lib/mysql
            - ./.config/mysqlconf/athena.conf:/etc/mysql/athena.conf
        env_file: ./.config/mysql.env
        ports:
            - "3310:3306"
