version: "3.7"

services:
    api:
        image: ledger:latest
        restart: unless-stopped
        command: ./ledger server
        env_file: .config/.env
        ports:
            - "55200:55200"
    worker:
        image: ledger:latest
        command: ./ledger worker
        restart: unless-stopped
        env_file: .config/.env
    redis:
        image: redis:6.2.5
        restart: unless-stopped
        container_name: ledger-redis
        env_file: .config/redis/.env
        command: >
            redis-server /etc/redis.conf
        volumes:
            - ./.data/redis:/data
            - ./.config/redis/redis.conf:/etc/redis.conf
networks:
    ledger-network:
